sudo: required
dist: bionic
os: linux
language: node_js
node_js:
  - '6'

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
    - gcc-8
    - g++-8

install:
  - dpkg --add-architecture i386
  - dpkg --print-foreign-architectures
  - apt-get -qq update || true
  - ./install.sh

script:
  - ./run.sh

env:
  - FLAVOR=normal
  - FLAVOR=community
  - FLAVOR=beta

before_install:
  - export TZ=Europe/Berlin
