sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update || true
  - sudo apt-get -qq install libc6:i386 libstdc++6:i386
  - sudo git clone --depth=50 --branch=master https://github.com/eq-3/occu /occu
  - sudo mkdir -p /etc/config /www/rega /config
  - sudo echo -e "#!/bin/bash\necho /bin/hm_startup executed" >/bin/hm_startup
  - sudo echo -e "#!/bin/bash\necho /bin/hm_autoconf executed" >/bin/hm_autoconf
  - sudo chmod a+x /bin/hm_startup /bin/hm_autoconf
  - sudo cp -v /occu/X86_32_Debian_Wheezy/packages-eQ-3/WebUI/etc/rega.conf /etc/
  - sudo cp -v /occu/X86_32_Debian_Wheezy/packages-eQ-3/WebUI/etc/config/InterfacesList.xml /etc/config/
  - sudo cp -v /occu/X86_32_Debian_Wheezy/packages-eQ-3/WebUI/bin/* /bin/
  - sudo mv -v /bin/ReGaHss /bin/ReGaHss.legacy
  - sudo cp -v homematic.regadom /etc/config/
  - sudo echo "/occu/X86_32_Debian_Wheezy/packages-eQ-3/WebUI/lib/" > /etc/ld.so.conf.d/hm.conf
  - sudo ldconfig
  - npm install

env:
  - FLAVOR=legacy
  - FLAVOR=normal
  - FLAVOR=community

before_install:
  - export TZ=Europe/Berlin
