sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update || true
  - sudo apt-get -qq install libc6:i386 libstdc++6:i386 expect-dev
  - sudo ./run-test.sh

env:
  - FLAVOR=normal
  - FLAVOR=community
  - FLAVOR=beta

before_install:
  - export TZ=Europe/Berlin
